---
name: PlayerSelectWatchingBlockEventLib
main: blugin\lib\PlayerSelectWatchingBlockEventLib
version: 1.0.0
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: '[lib] Implement the event called when player repeat crouching with seeing block.'
load: STARTUP
...
